### PR TITLE
test(e2e): add tests for metrics with TLS enabled

### LINKED ISSUE #5428: [Bug]: E2E metrics tests are using a fixed http schema
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The E2E tests are not properly detecting if the metrics port are HTTP or HTTPS, hence, tests may fail if someone enables the HTTPS the tests will fail.

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sxd**
Add end-to-end tests to ensure monitoring metrics work correctly with TLS enabled.

Closes #5428

### CODE REVIEW

**Review by mnencia — APPROVED** [review]

**Comment by litaocdl** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10711711845

**Review by litaocdl — APPROVED** [review]

**Comment by litaocdl** [comment]
Remove the backport to 1.23 and 1.22, as monitoring.tls is only in 1.24 above. @mnencia

**Pull request merged**
