### PR TITLE
fix: pull_request_target disorder

### LINKED ISSUE #982: fix disorder caused by `pull_request_target` event
We previously decided to use `pull_request_target` instead of `pull_request` because we want to enable the PR from a forked repo to perform the E2E testing (which needs to access a few secrets). However, the default behavior for the `pull_request_target` triggered workflow is to `check out` the code per the base of the PR, aka. the `main` branch, which is confused when a PR fixes an issue on `main` but the workflow triggered by `pull_request_target` still fails.

### PR DESCRIPTION
**Pull request by hh24k**
1. Specify the `ref` as `${{ github.event.pull_request.head.sha }}` in case workflows triggered by `pull_request_target` perform E2E testing per `main` branch`
2. Add the listening of `pull_request` events because even with the `ref` specified, the workflow triggered by `pull_request_target` still can not test per the changes in a workflow itself.
3. Add a check to make only PRs from a forked repo trigger the events of `pull_request_target` in case a PR from this repo triggers both `pull_request` and `pull_requeset_target` and causes duplicated workflow running.

Closes #982 

Signed-off-by: Hai He hai.he@enterprisedb.com

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

**Review by litaocdl — APPROVED** [review]

**Review by NiccoloFei — APPROVED** [review]

**Comment by NiccoloFei** [comment]
These changes have been superseded by https://github.com/cloudnative-pg/cloudnative-pg/pull/1084. Closing this PR.

**Pull request closed without merging**
