### PR TITLE
docs(plugin): standardize the `CLUSTER` argument in plugin commands

### LINKED ISSUE #5848: [Docs]: Standardize the cluster name argument in kubectl cnpg plugin
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

In the plugin we use different names to refert to a cluster like:
* cluster
* cluster_name
* clusterName
* <clusterName>
We should standarize the word we use to refer a cluster 

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pchovelon**
This update ensures consistent usage of the `CLUSTER` argument across all plugin commands and their associated documentation.  

Closes #5848

### CODE REVIEW

**Comment by gbartolini** [comment]
Hey @pchovelon, thanks for your contribution!

I think the change should also involve the actual plugin. For example, try:

 ```sh
kubectl cnpg report cluster --help
```

It will return something like:

 ```console
Usage:
  kubectl cnpg report cluster <clusterName> [flags]
 ```

**Comment by pchovelon** [comment]
> Do you think you can give it a spin? :)

Not the funniest job ^^ but done :+1: 

no more `cluster_name`, no more `cluster_name`
```sh
➜  cloudnative-pg git:(dev-5848) grep -R "clusterName>" internal/cmd/plugin 
➜  cloudnative-pg git:(dev-5848) grep -R "cluster_name" internal/cmd/plugin

```

**Comment by gbartolini** [comment]
Oh ... see #6259 didn't know there was another PR

**Comment by gbartolini** [comment]
Let me fix this. I will merge the two prs

**Review by gbartolini — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Comment by gbartolini** [comment]
@pchovelon I see you have not signed your contributions. Can you at least confirm here you are OK with me adding your email as sign off?

**Comment by pchovelon** [comment]
> @pchovelon I see you have not signed your contributions. Can you at least confirm here you are OK with me adding your email as sign off?

Yep that's fine.

**Comment by pchovelon** [comment]
I see that [cluste] is still used in internal/cmd/plugin/pgbench/pgbench.go;

**Pull request merged**
