### PR TITLE
fix: updating resizing status if resize is pending

### LINKED ISSUE #134: Update status if pvc resize is pending
Currently we update the status of the cluster if a resize is happening but there are scenarios where a resize could be pending for a non trivial amount of time. In these instances we should update the Cluster status to reflect that a resize is scheduled to happen but has yet to happen.

### PR DESCRIPTION
**Pull request by jlong49**
Closes #134

### CODE REVIEW

**Review by mnencia — APPROVED** [review]

**Review by sxd — APPROVED** [review]

**Review by gbartolini — APPROVED** [review]

**Comment by gbartolini** [comment]
While writing the release notes, I could not figure out why we are doing this. Are we sure we want to ship this in the next patch release? This is our last chance to revert it.

**Comment by jlong49** [comment]
We thought this change was needed but no longer do. This can be reverted.

**Comment by gbartolini** [comment]
Also we don't have any E2E tests written for this. It seems a bit lame to me to proceed. I'd rather postpone this when we have a clearer idea about why we need this and what we need to do to test it works. Do you agree?

**Comment by leonardoce** [comment]
Yes, this can be reverted. Unfortunately the underlying context is not clear here too.

**Pull request merged**
