### PR TITLE
fix(scheduled-backups): manage unsatisfiable schedules

### LINKED ISSUE #5108: [Bug]:  A backup object will be created immediately if a cron expression indicates an impossible time to occur
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

When I create a `ScheduledBackup` object with `schedule`  **\* * * 30 2 \*** as following 
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-example
spec:
  schedule: "* * * 30 2 *"
  cluster:
    name: pg-backup
```

the backup object is created immediately, 
```
 k get backup -w
NAME                            AGE   CLUSTER       METHOD              PHASE       ERROR
backup-example-00010101000000   31s   test-backup   barmanObjectStore   completed
```
However, the corn expression `* * * 30 2 *` (Feb 30th) indicates an impossible time to occur.  The ScheduledBackup reconciler should never create a backup 

### Cluster resource

_No response_

### Relevant log output

```
{"level":"debug","ts":"2024-07-19T08:52:53Z","msg":"reconciling object `default/backup-example`","controller":"scheduledbackup","controllerGroup":"postgresql.cnpg.io","controllerKind":"ScheduledBackup","ScheduledBackup":{"name":"backup-example","namespace":"default"},"namespace":"default","name":"backup-example","reconcileID":"f64199a3-3593-4175-afdf-3e1c5ef25008","caller":"internal/controller/scheduledbackup_controller.go:68"}
{"level":"info","ts":"2024-07-19T08:52:53Z","msg":"Next backup schedule","controller":"scheduledbackup","controllerGroup":"postgresql.cnpg.io","controllerKind":"ScheduledBackup","ScheduledBackup":{"name":"backup-example","namespace":"default"},"namespace":"default","name":"backup-example","reconcileID":"f64199a3-3593-4175-afdf-3e1c5ef25008","next":"0001-01-01T00:00:00Z"}
{"level":"info","ts":"2024-07-19T08:52:53Z","msg":"Creating backup","controller":"scheduledbackup","controllerGroup":"postgresql.cnpg.io","controllerKind":"ScheduledBackup","ScheduledBackup":{"name":"backup-example","namespace":"default"},"namespace":"default","name":"backup-example","reconcileID":"f64199a3-3593-4175-afdf-3e1c5ef25008","backupName":"backup-example-00010101000000"}
{"level":"error","ts":"2024-07-19T08:52:53Z","msg":"Error while creating backup object","controller":"scheduledbackup","controllerGroup":"postgresql.cnpg.io","controllerKind":"ScheduledBackup","ScheduledBackup":{"name":"backup-example","namespace":"default"},"namespace":"default","name":"backup-example","reconcileID":"f64199a3-3593-4175-afdf-3e1c5ef25008","backupName":"backup-example-00010101000000","error":"backups.postgresql.cnpg.io \"backup-example-00010101000000\" already exists","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.createBackup\n\tinternal/controller/scheduledbackup_controller.go:272\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.ReconcileScheduledBackup\n\tinternal/controller/scheduledbackup_controller.go:215\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.(*ScheduledBackupReconciler).Reconcile\n\tinternal/controller/scheduledbackup_controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/Users/huyantian/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/huyantian/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/huyantian/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/huyantian/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}
{"level":"debug","ts":"2024-07-19T08:52:53Z","msg":"object `default/backup-example` has been reconciled","controller":"scheduledbackup","controllerGroup":"postgresql.cnpg.io","controllerKind":"ScheduledBackup","ScheduledBackup":{"name":"backup-example","namespace":"default"},"namespace":"default","name":"backup-example","reconcileID":"f64199a3-3593-4175-afdf-3e1c5ef25008","caller":"internal/controller/scheduledbackup_controller.go:71"}
{"level":"error","ts":"2024-07-19T08:52:53Z","msg":"Reconciler error","controller":"scheduledbackup","controllerGroup":"postgresql.cnpg.io","controllerKind":"ScheduledBackup","ScheduledBackup":{"name":"backup-example","namespace":"default"},"namespace":"default","name":"backup-example","reconcileID":"f64199a3-3593-4175-afdf-3e1c5ef25008","error":"backups.postgresql.cnpg.io \"backup-example-00010101000000\" already exists","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/huyantian/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/huyantian/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/huyantian/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}
```
_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by YanniHu1996**
Modify the ScheduledBackup reconciler to add an event to the resource when the proposed schedule doesn't permit a subsequent execution.

This patch addresses a previous issue where the reconciler would erroneously create a backup with an incorrect timestamp under such conditions. The event notifies users about the schedule constraint, enhancing the reliability of the backup process.

closes: #5108

### CODE REVIEW

**Comment by YanniHu1996** [comment]
the e2e from the fork:
 https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10033710805

**Comment by leonardoce** [comment]
Hi @YanniHu1996.

Unfortunately, I can't reproduce the problem with the example you shared in #5138.
After the reconciliation of the `ScheduledBackup`, I just get:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  annotations: [...]
  creationTimestamp: "2024-07-23T09:43:16Z"
  generation: 1
  managedFields: [...]
  name: backup-example
  namespace: default
  resourceVersion: "9454"
  uid: 72e8f227-a60a-44df-a43d-2c8e727b9dab
spec:
  backupOwnerReference: none
  cluster:
    name: cluster-example-with-backup
  method: barmanObjectStore
  schedule: 0 0 0 30 2 0
status:
  lastCheckTime: "2024-07-23T09:43:16Z"
```

Can you please check if this happens with the latest main? I'm on commit 39846aa38fe06e2e53a4f9b2d96d60fb9da4f693

**Comment by YanniHu1996** [comment]
Hi @leonardoce , I can reproduce this problem on https://github.com/cloudnative-pg/cloudnative-pg/commit/39846aa38fe06e2e53a4f9b2d96d60fb9da4f693

the`Cluster` yaml 
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-backup
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  backup:
    target: primary
    barmanObjectStore:
      destinationPath: s3://cluster-test-backup/
      endpointURL: http://minio-service.minio:9000
      s3Credentials:
        accessKeyId:
          name: s3-cred
          key: ID
        secretAccessKey:
          name: s3-cred
          key: KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        immediateCheckpoint: true

  storage:
    size: 1Gi
```

the `ScheduledBackup` yaml
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  annotations:
  name: backup-example
spec:
  schedule: "* * * 30 2 *"
  backupOwnerReference: none
  method: barmanObjectStore
  cluster:
    name: test-backup
```

the output 
```sh
k get backups
NAME                            AGE    CLUSTER       METHOD              PHASE       ERROR
backup-example-00010101000000   3m2s   test-backup   barmanObjectStore   completed
```

**Comment by YanniHu1996** [comment]
the reason here is that cron expression

the cron parses the `"0 0 0 30 2 0"` you provided to `2025-02-02 00:00:00 +0000 UTC` 

the cron parses the `"* * * 30 2 *"` to `0001-01-01 00:00:00 +0000 UTC`

**Comment by leonardoce** [comment]
@YanniHu1996 I just used the ScheduledBackup [you provided](https://github.com/cloudnative-pg/cloudnative-pg/issues/5108#issue-2418228338):

```
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-example
spec:
  schedule: "0 0 0 30 2 0"
  cluster:
    name: pg-backup
```

If this example works, can you fix the original issue you opened?

**Comment by YanniHu1996** [comment]
Hi @leonardoce Thanks! I have fixed the sample in that issue

**Comment by leonardoce** [comment]
With the reviewed patch, we get something like this:

```
$ kubectl describe scheduledbackups.postgresql.cnpg.io  backup-example
Name:         backup-example
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  postgresql.cnpg.io/v1
Kind:         ScheduledBackup
Metadata:
  Creation Timestamp:  2024-07-23T13:08:16Z
  Generation:          1
  Managed Fields: [...]
  Resource Version:  35996
  UID:               49972cfd-20ca-4ada-a35b-40e9d5529b44
Spec:
  Backup Owner Reference:  none
  Cluster:
    Name:    pg-backup
  Method:    barmanObjectStore
  Schedule:  * * * 30 2 *
Events:
  Type     Reason      Age   From                            Message
  ----     ------      ----  ----                            -------
  Warning  NoSchedule  5s    cloudnative-pg-scheduledbackup  No time satisfying the schedule "* * * 30 2 *" have been found
```

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10059624939

**Comment by mnencia** [comment]
/ok-to-merge tests all green on the fork

**Review by mnencia — APPROVED** [review]

**Review by gabriele-wolfox — APPROVED** [review]

**Comment by gabriele-wolfox** [comment]
LGTM

**Review by leonardoce — APPROVED** [review]

**Pull request merged**
