### PR TITLE
feat: backup target policy implemented

### LINKED ISSUE #1140: Add `backup.target` option to enable backup from a standby
Currently CloudNativePG only performs a backup from a primary, despite both PostgreSQL and Barman (cloud) supporting backup from standbys too.

Historically, the advantage of taking a backup from a standby is to reduce I/O workload on the primary while the file system is literally scanned entirely to fetch the database pages.

Enhance the `backup` stanza of the `Cluster` resource to support the `target` option, accepting at the moment these two values:

- `primary`: informing the operator to elect the primary as the target of the backup (default)
- `prefer-standby`: informing the operator to select any ready standby or fallback to the primary

If possible select the least lagging.

Feel free to rediscuss this in the analysis phase.

### PR DESCRIPTION
**Pull request by phisco**
Closes #1140.

This patch introduces the `.spec.backup.target` field in Clusters, which allows to specify a backup target policy, describing which instance should run backups. Possible current values are:
- `primary`: default, previous behaviour, backups will always be run on Cluster's primary instance.
- `prefer-standby`: backups will preferably run on secondary instances if present.

Signed-off-by: Philippe Scorsolini <p.scorsolini@gmail.com>

### CODE REVIEW

**Comment by phisco** [comment]
WIP: still needs docs and tests

**Comment by phisco** [comment]
feel free to squash everything before merging

**Review by gbartolini — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Comment by mnencia** [comment]
@phisco @armru @gbartolini I will merge this as soon as the test run terminates successfully.

**Comment by phisco** [comment]
@mnencia awesome, thank you all!

**Pull request merged**
