### PR TITLE
chore: move PodStatus to API package

### PR DESCRIPTION
**Pull request by leonardoce**
The `PodStatus` is now part of the API package, as is it referred by the API
itself.

See: #3762

### CODE REVIEW

**Review by fcanovai — APPROVED** [review]

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/11016947987

**Review by mnencia — APPROVED** [review]

**Comment by leonardoce** [comment]
The E2e run was fully green

**Pull request merged**
