### PR TITLE
chore: refresh licenses directory

### PR DESCRIPTION
**Pull request by mnencia**

### CODE REVIEW

**Review by sxd — APPROVED** [review]

**Comment by mnencia** [comment]
I have created #5393 to automate this manual process.

**Review by NiccoloFei — APPROVED** [review]

**Comment by mnencia** [comment]
I think we should hold merging this so we have something to test implementing #5393

**Comment by mnencia** [comment]
we agreed to merge this PR. The testing of the automation will be done in a different way.

**Pull request merged**
