### PR TITLE
feat: allow additional args to be passed to `barman-cloud-wal-restore`

### LINKED ISSUE #5096: [Feature]: allow additionalCommandArgs to be passed to `barman-cloud-wal-restore`
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

The operator currently supports `additionalCommandArgs` for `barman-cloud-backup` and `barman-cloud-wal-archive`. To ensure completeness, we should also add support for additional arguments to `barman-cloud-wal-restore`.

### Describe the solution you'd like

Since the `additionalCommandArgs` for archiving has not yet been released, I suggest renaming it to `archiveAdditionalCommandArgs` and introducing `restoreAdditionalCommandArgs`.

The `restoreAdditionalCommandArgs` parameter would affect replicas within the same cluster when specified in the backup stanza. Additionally, it would impact the restore process from remote locations when specified in the externalCluster stanza.

### Describe alternatives you've considered

An alternative could be to leave the field driving the WAL archiving as it is and only add the new parameter, but I wouldn't say I like the solution because it is not symmetrical.

### Additional context

_No response_

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mnencia**
Closes #5096

### CODE REVIEW

**Comment by leonardoce** [comment]
The code looks good to me. I'm starting a full E2e run.

**Comment by leonardoce** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9959440555

**Review by armru — APPROVED** [review]

**Comment by armru** [comment]
if the tests are green we can merge

**Review by leonardoce — APPROVED** [review]

**Pull request merged**
