### PR TITLE
fix: ignore ServerName mismatch in internal TLS

### LINKED ISSUE #4885: [Bug]: TLS verification will fail with user provided server certificate
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

trunk (main)

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

When you provide valid global certificates for the servers, it is not guaranteed that they contain the <cluster-name>-rw DNS name, as usually, the certificate emitter cannot verify it; thus, the name is not included in the final certificate. That's why the [streaming connection to the primary](https://github.com/cloudnative-pg/cloudnative-pg/blob/bb8fc8439b0f3c8701feab8ff33eecdaf97a014f/pkg/management/postgres/conninfo.go#L38) is configured with `sslmode=verify-ca` instead of full certification.

The operator must use the same verification level when speaking with the instance.

In the future, we can consider configuring this behavior in the Cluster CR.

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mnencia**
Make the operator verify server certificates against the CA only, disregarding the DNS name.
This is to match what PostgreSQL does for communication within the cluster, avoiding errors in the operator communications where Postgres accepts the certificates. 

Closes #4885

### CODE REVIEW

**Review by armru — APPROVED** [review]

**Comment by mnencia** [comment]
E2E running on EDB fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9611995929

**Review by sxd — APPROVED** [review]

**Comment by mnencia** [comment]
This is related to #4936

**Review by gbartolini — APPROVED** [review]

**Pull request merged**
