### PR TITLE
refactor: centralize webserver client logic

### PR DESCRIPTION
**Pull request by armru**
This patch centralizes all the logic regarding the webserver clients inside one package instead of having it scattered around the codebase

### CODE REVIEW

**Review by mnencia — APPROVED** [review]

**Comment by gbartolini** [comment]
I think given that we are releasing RC1, this is a good time to slip this in.

**Review by gabriele-wolfox — APPROVED** [review]
LGTM

**Review by gbartolini — APPROVED** [review]

**Comment by gbartolini** [comment]
I am merging this as we are launching RC1. All tests pass.

**Pull request merged**
