### PR TITLE
chore: update controller-gen 0.11.1 to 0.11.3

### PR DESCRIPTION
**Pull request by sxd**

### CODE REVIEW

**Review by jlong49 — APPROVED** [review]

**Review by jsilvela — APPROVED** [review]

**Comment by mnencia** [comment]
Please regenerate the manifests.

**Review by mnencia — APPROVED** [review]

**Comment by phisco** [comment]
Shouldn't this be handled by renovate? 🤔

**Comment by sxd** [comment]
@phisco it's to fix another backport that update the version I think renovate wants to update to another version

**Pull request merged**
