### PR TITLE
Remove MinIO Gateway from docs as it's deprecated

### PR DESCRIPTION
**Pull request by dvaldivia**
Hi, since the MinIO Gateway was [deprecated about a year ago](https://blog.min.io/deprecation-of-the-minio-gateway/) so this PR removes it from the documentation.

If the maintainers are ok with it I could replace it with detailed documentation on how to use `MinIO Operator` instead.

Signed-off-by: Daniel Valdivia <hola@danielvaldivia.com>

### CODE REVIEW

**Comment by mnencia** [comment]
> If the maintainers are ok with it I could replace it with detailed documentation on how to use `MinIO Operator` instead.

I would like to have the new documentation ready before removing the old one

**Comment by sxd** [comment]
@dvaldivia I'm totally agree with Marco, can we have something that replace this? we need to provide an alternative and that will be great

**Comment by dvaldivia** [comment]
@sxd @mnencia there's no replacement for Gateway, but I'll update it with Operator so users have an alternative, additionally I was planning a blog post on CloudNative-PG + MinIO Operator so I'll grab some of those instructions but focus on YAML just like the rest of the documentation

**Comment by sxd** [comment]
@dvaldivia that will be great! a blog post plus the documentation will help a lot of people that usually ask how to configure MinIO to be used with CloudNativePG, thanks for that in advance!

**Comment by gbartolini** [comment]
> @sxd @mnencia there's no replacement for Gateway, but I'll update it with Operator so users have an alternative, additionally I was planning a blog post on CloudNative-PG + MinIO Operator so I'll grab some of those instructions but focus on YAML just like the rest of the documentation

That'd be awesome. Thanks.

**Comment by sxd** [comment]
@dvaldivia do you have any news on this PR? will be great to have it merged by 1.20 which will be in the next release cycle

**Comment by sxd** [comment]
Hi,

I'm closing this PR since we haven't had news for the last couple of weeks

**Pull request closed without merging**
