### PR TITLE
chore: enables the customization of leaseDuration and renewDeadline in the controller manager

### LINKED ISSUE #758: allow the customization of `leaseDuration` and `renewDeadline` for the controller manager
We currently support the configuration of the leader election for the manager without allowing the customization of the`leaseDuration` and `renewDeadline` parameters.

We should proceed to add those parameters given that they are strictly related to making the leader election work properly.

https://github.com/cloudnative-pg/cloudnative-pg/blob/29b4d0d1085cfa3b2b48f05c2b31d3c72a40c660/internal/cmd/manager/controller/cmd.go#L24

https://github.com/cloudnative-pg/cloudnative-pg/blob/29b4d0d1085cfa3b2b48f05c2b31d3c72a40c660/internal/cmd/manager/controller/controller.go#L103

### PR DESCRIPTION
**Pull request by armru**
This patch makes it possible to customize `leaseDuration` and `renewDeadline` in the controller manager.

Closes #758

Signed-off-by: Armando Ruocco <armando.ruocco@enterprisedb.com>

### CODE REVIEW

**Review by jsilvela — APPROVED** [review]

**Review by gbartolini — APPROVED** [review]

**Review by leonardoce — APPROVED** [review]

**Comment by leonardoce** [comment]
This is fine with me. I'm waiting for the CI to complete and for a clean e2e run

**Comment by leonardoce** [comment]
The E2e were running fine, I'm rebasing it and merging it

**Pull request merged**
