### PR TITLE
feat: add PDB to the plugin `status` command

### LINKED ISSUE #4019: [Feature]: Display PDB in `cnpg status`
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We don't show if PodDisruptionBudgets are present in a cluster.

### Describe the solution you'd like

Following the introduction of configurable pod disruption budgets (#3837), we should easily show in the `cnpg status` command. Ideally, we should check if the cluster has any PDB objects associated to it, instead of relying on the new `enablePDB` option.

### Describe alternatives you've considered

N/A

### Additional context

_No response_

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by armru**
Closes #4019

### CODE REVIEW

**Comment by leonardoce** [comment]
This is the output with no PDBs

```
➜ ./bin/kubectl-cnpg status cluster-example
Cluster Summary
Name:                cluster-example
Namespace:           default
System ID:           7360704659976978458
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:16.2
Primary instance:    cluster-example-1
Primary start time:  2024-04-22 14:53:30 +0000 UTC (uptime 7m54s)
Status:              Cluster in healthy state
Instances:           3
Ready instances:     3
Current Write LSN:   0/7000110 (Timeline: 1 - WAL File: 000000010000000000000007)

Certificates Status
Certificate Name             Expiration Date                Days Left Until Expiration
----------------             ---------------                --------------------------
cluster-example-ca           2024-07-21 14:48:18 +0000 UTC  89.99
cluster-example-replication  2024-07-21 14:48:18 +0000 UTC  89.99
cluster-example-server       2024-07-21 14:48:18 +0000 UTC  89.99

Continuous Backup status
Not configured

Physical backups
No running physical backups found

Streaming Replication status
Replication Slots Enabled
Name               Sent LSN   Write LSN  Flush LSN  Replay LSN  Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority  Replication Slot
----               --------   ---------  ---------  ----------  ---------  ---------  ----------  -----      ----------  -------------  ----------------
cluster-example-2  0/7000110  0/7000110  0/7000110  0/7000110   00:00:00   00:00:00   00:00:00    streaming  async       0              active
cluster-example-3  0/7000110  0/7000110  0/7000110  0/7000110   00:00:00   00:00:00   00:00:00    streaming  async       0              active

Unmanaged Replication Slot Status
No unmanaged replication slots found

Managed roles status
No roles managed

Tablespaces status
No managed tablespaces

PodDisruptionBudgets status
No active PodDisruptionBudgets found

Instances status
Name               Database Size  Current LSN  Replication role  Status  QoS         Manager Version  Node
----               -------------  -----------  ----------------  ------  ---         ---------------  ----
cluster-example-1  29 MB          0/7000110    Primary           OK      BestEffort  1.22.2           pg-operator-e2e-v1-29-2-control-plane
cluster-example-2  29 MB          0/7000110    Standby (async)   OK      BestEffort  1.22.2           pg-operator-e2e-v1-29-2-control-plane
cluster-example-3  29 MB          0/7000110    Standby (async)   OK      BestEffort  1.22.2           pg-operator-e2e-v1-29-2-control-plane
```

**Comment by leonardoce** [comment]
E2e test suite: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8786369936

**Comment by leonardoce** [comment]
E2e tests should not be impacted by this (tm) but better to be safe than sorry!

**Comment by jsilvela** [comment]
I've made small changes for cosmetics. The `Desired Healthy` IMO is a bit confusing.
This is what we'd now see:

```
Pod Disruption Budgets status
Name                     Role     Expected Pods  Current Healthy  Minimum Desired Healthy  Disruptions Allowed
----                     ----     -------------  ---------------  -----------------------  -------------------
cluster-example          replica  2              2                1                        1
cluster-example-primary  primary  1              1                1                        0
```

**Review by jsilvela — APPROVED** [review]

**Comment by jsilvela** [comment]
@leonardoce I think you forgot to approve? Also please see my change...

**Review by leonardoce — APPROVED** [review]

**Comment by leonardoce** [comment]
> @leonardoce I think you forgot to approve? Also please see my change...

Yes! Approved

**Pull request merged**
