### PR TITLE
fix(database): remove 'deleteDatabase' finalizer from orphan Database CRD

### LINKED ISSUE #5593: [split from `#4679`]: Operator should prune finalizers from Database when orphaned
We might also prune finalizers from other objects. C.f. https://github.com/cloudnative-pg/cloudnative-pg/pull/5581

### PR DESCRIPTION
**Pull request by gabriele-wolfox**
Closes #5593

### CODE REVIEW

**Comment by jsilvela** [comment]
I saw the other PR that was doing finalizer cleanup, #5581 , has been closed as unnecessary.
Given that, isn't having a dedicated file `internal/controller/finalizers_delete.go` a bit too big?
We already have `internal/controller/cluster_delete.go` which seems perfect for this.
And similar with the new dedicated file `pkg/utils/finalizers.go`. A new file just for one entry?

**Comment by gabriele-wolfox** [comment]
> I saw the other PR that was doing finalizer cleanup, #5581 , has been closed as unnecessary. Given that, isn't having a dedicated file `internal/controller/finalizers_delete.go` a bit too big? We already have `internal/controller/cluster_delete.go` which seems perfect for this. And similar with the new dedicated file `pkg/utils/finalizers.go`. A new file just for one entry?

@jsilvela , I like the idea to split the work around finalizers inside separated files.
But if you prefer differently, feel free to move/refactor the code around.

**Comment by jsilvela** [comment]
No strong feeling there @gabriele-wolfox , will leave to the second reviewer. This PR looks good.

**Review by jsilvela — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Pull request merged**
