### PR TITLE
feat(pgbouncer): support pgbouncer 1.23.0 in the metrics collector

### LINKED ISSUE #5043: [Bug]: pgbouncer metrics e2e not working
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.23.2

### What version of Kubernetes are you using?

1.30 (unsupported)

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

The metrics tests are failing on branch release-1.22 
CI failure https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/9839487066

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sxd**
The latest version of pgBouncer added a new metric in this PR https://github.com/pgbouncer/pgbouncer/pull/727
this patch adds that metric to the list of exported ones generated by `SHOW STATS` while retaining the backward compatibility

Closes #5043

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

**Comment by gbartolini** [comment]
@sxd what about pgbouncer < 1.23? Will this change break those installations? I would have expected a conditional build of the SHOW STATS query.

**Comment by gbartolini** [comment]
I have conservatively tagged this as "do not merge" waiting for the above clarification.

**Review by leonardoce — APPROVED** [review]

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
I tested manually with 1.22.1 and 1.23.0 and everything looks fine. I just fixed the warnings raised by the linter.

**Comment by leonardoce** [comment]
Started an E2e run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9856345151

**Comment by leonardoce** [comment]
E2e tests are all green! I'm merging it.

**Pull request merged**
