### PR TITLE
chore: restore the ability to use PVCs as source for a restore

### LINKED ISSUE #5030: [Chore]: restore the possibility to use PVCs as recovery source
### Description

The current API allows specifying the type of object to use as the recovery source. Previously, it was possible to enable recovery from a set of existing Persistent Volume Claims (PVCs). However, this functionality was lost when safety checks using snapshot metadata were introduced.

While snapshots provide comprehensive safety measures, the ability to recover from a set of PVCs remains valuable for troubleshooting and experimentation purposes. Although this method lacks the safety guarantees of snapshots, it can be a crucial tool in non-production environments.

### Proposal

I propose reinstating the ability to use PVCs as a recovery source. This approach will be explicitly unsupported in production and will require that the source PVCs are not actively used by a running PostgreSQL instance.

Restoring this functionality will enhance the flexibility and usability of the recovery process, especially in development and testing scenarios.

### PR DESCRIPTION
**Pull request by mnencia**
Closes #5030

### CODE REVIEW

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
The is fine with me. I started a full E2e suite run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9840725538

**Review by leonardoce — APPROVED** [review]

**Comment by redbaron** [comment]
Why this PR is not included in 1.23.3 release notes?

**Comment by Routhinator** [comment]
Not sure it works? 

```yaml
      bootstrap:
        recovery:
          volumeSnapshots:
            storage:
              name: db-recovery
              kind: PersistentVolumeClaim
              apiGroup: v1
```

Is this not approximately what the code should expect?

Rejects it with the error in the PR so it's got this commit.

```
│ Error: cannot patch "nextcloud-db" with kind Cluster: admission webhook "vcluster.cnpg.io" denied the request: Cluster.cluster.cnpg.io "nextcloud-db" is invalid: spec.bootstrap.recovery.storage: Invalid value: v1.TypedLocalObjectReference{APIGroup:(*string)(0xc001291a00), Kind:"PersistentVolumeClaim", Name:"db-recovery"}: Only VolumeSnapshots and PersistentVolumeClaims are supported
```

Based on my read of the code, that's what it should be expecting.

**Pull request merged**
