### PR TITLE
ci: Make the operator log level configurable in e2e test suite

### PR DESCRIPTION
**Pull request by litaocdl**
This patch make the operator log level configurable in e2e test suite, and 
expose the configuration into workflow dispatch and /test slash command options

Closes: #1086 
Signed-off-by: Tao Li <tao.li@enterprisedb.com>

### CODE REVIEW

**Comment by litaocdl** [comment]
Backport success of this commit depends on cherry-pick of previous commit 
https://github.com/cloudnative-pg/cloudnative-pg/commit/32fd0b6baeedb2d1f4cd6d376b63c8595cda4978

**Review by jsilvela — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Pull request merged**
