### PR TITLE
feat: enable configuration of `archive_mode`

### PR DESCRIPTION
**Pull request by leonardoce**
Allow users to disable `archive_mode`.

Closes: #3774

### CODE REVIEW

**Review by gbartolini — APPROVED** [review]

**Review by sxd — APPROVED** [review]

**Comment by gbartolini** [comment]
It looks like we need to fix the `always` check as E2E tests fail with:

```
#1: admission webhook "vcluster.cnpg.io" denied the request: Cluster.postgresql.cnpg.io "cluster-replica-tls" is invalid: spec.postgresql.parameters.archive_mode: Invalid value: "always": archive_mode=always is directly managed by the operator
```

**Comment by leonardoce** [comment]
E2e tests are now green

**Review by gbartolini — APPROVED** [review]

**Comment by gbartolini** [comment]
Trying this patch, it is clear that it requires a change of API in the case of promotion of a replica cluster.

**Comment by gbartolini** [comment]
We should either go with a new option or - probably better in this phase - an annotation (similarly to what we already have for the skip check of the WAL archive)

**Comment by gbartolini** [comment]
Superseded by #4055

**Pull request closed without merging**
