### PR TITLE
chore: important changes to default values

### PR DESCRIPTION
**Pull request by litaocdl**
close: #1950

### CODE REVIEW

**Review by jsilvela — APPROVED** [review]

**Review by jlong49 — APPROVED** [review]

**Review by armru — APPROVED** [review]

**Comment by gbartolini** [comment]
I would use this as commit message:

```
feat: change in default behavior for primary update method and backup target

CloudNativePG 1.20 introduces some changes to the default behavior of a
few features for newly created `Cluster` resources, compared to previous
versions of the operator. The goal of these changes is to improve the
resilience of a Postgres cluster out of the box through convention over
configuration. For clusters with one or more replicas:

- Backup from standby is now enabled by default, unless `target` is
   explicitly set to `primary`
- Restart of the primary is now the default method to complete the
   unsupervised rolling update procedure (`primaryUpdateMethod`
   defaults to `restart`, unless explicitly set to `switchover`)

Closes #1950
```

**Pull request merged**
