### PR TITLE
fix: pgbasebackup cluster join wal_sender_timeout configuration

### PR DESCRIPTION
**Pull request by augustoribeiro**
Removing _wal_sender_timeout_  on pgbasebackup joining cluster. This PR is similar to #3586 but fixes the problem for nodes joining a cluster.

### CODE REVIEW

**Comment by leonardoce** [comment]
Tests running here: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8172415285

**Comment by leonardoce** [comment]
The failures are not related to this PR. Let's have another run!

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8236189637

**Review by leonardoce — APPROVED** [review]

**Comment by leonardoce** [comment]
Everything green. We need another review now.

**Review by mnencia — APPROVED** [review]

**Pull request merged**
