### PR TITLE
chore: remove the use of cURL pod in the e2e tests

### LINKED ISSUE #4942: [Feature]: Remove the use of curl inside the E2E tests
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

We create a pod just to have curl inside and this should be avoided for sure.

### Describe the solution you'd like

Use a proxy to get get information when curl is required 

### Describe alternatives you've considered

none

### Additional context

_No response_

### Backport?

Yes

### Are you willing to actively contribute to this feature?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sxd**
Closes #4942

### CODE REVIEW

**Review by YanniHu1996 — APPROVED** [review]

**Review by jsilvela — APPROVED** [review]

**Comment by mnencia** [comment]
Full E2E running on EDB fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9677948692

**Review by mnencia — APPROVED** [review]

**Pull request merged**
