### PR TITLE
test: add Openshift as a new CloudVendor in the E2E suite

### PR DESCRIPTION
**Pull request by sxd**
This patch adds Openshift as a new available CloudVendor in the E2E test suite, as well as a set of 
utility functions to assist testing cnpg deployed in an Openshift cluster.
Upgrade Path E2Es are also added, testing the upgrade of the operator via OLM Subscription.

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

**Comment by litaocdl** [comment]
test run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/7568038209/job/20608551490

**Review by jsilvela — APPROVED** [review]

**Review by NiccoloFei — APPROVED** [review]

**Comment by NiccoloFei** [comment]
Smoke E2E test run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/7714637374
Full E2E test run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/7700172090

**Review by mnencia — APPROVED** [review]

**Comment by mnencia** [comment]
Another test to verify that the changes have not broken the non-openshift tests https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/7738311485

**Review by mnencia — CHANGES_REQUESTED** [review]
We need a proper commit message and i think that the report plugin changes deserve a separate PR.

**Comment by NiccoloFei** [comment]
New run on local (smoke): https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/7741493608
New run on openshift (smoke): https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/7741505123

**Review by mnencia — APPROVED** [review]

**Review by mnencia — CHANGES_REQUESTED** [review]
I don't see any documentation change

**Review by mnencia — APPROVED** [review]
Documentation will be updated in #3769

**Pull request merged**
