### PR TITLE
fix(externalcluster): sslmode is set based on the passed parameters

### LINKED ISSUE #392: Monolith database import is requiring a TLS connection
We're currently requiring a TLS connection between the CNP cluster to be created and the PostgreSQL instance we're downloading data from but just from the **monilith** import approach, but we don't to that for the **microservice** approach.

The reason behind this is that the microservice approach is going to create a connection from the instance manager to the source PostgreSQL instance using **lib/pq** which is by setting `sslmode` to `required` by default.
Unfortunately TLS is not commonly configured for development databases; see [this article](https://errorsingo.com/github.com-lib-pq-err-ssl-not-supported/) for more information.

We should check whether it's best to document this behavior or change our implementation to make the monolith and the microservice approach have the same requirements.

### LINKED ISSUE #571: we should ensure that the dbname is removed when creating the connection pooler for the imports
In our code, we create but don't use the modified `externalCluster` struct with the `dbname` `connectionParameter` removed.

We should fix this, as the connection string without dbname is needed to avoid crashes during the creation of the various import connection strings

https://github.com/cloudnative-pg/cloudnative-pg/blob/bc15477ae116d9c923edf614b78a2645cac04dfa/pkg/management/postgres/initdb.go#L386

### PR DESCRIPTION
**Pull request by armru**
This PR contains two fixes. For the description see the relative commits

Closes #392
Closes #571

Signed-off-by: Armando Ruocco <armando.ruocco@enterprisedb.com>

### CODE REVIEW

**Comment by armru** [comment]
We should document the sslmode election behavior

**Review by leonardoce — APPROVED** [review]

**Comment by armru** [comment]
Do not squash the commits

**Comment by leonardoce** [comment]
@armru can you please add a paragraph to the documentation explaining the behavior we implement? Thank you!

**Review by gbartolini — APPROVED** [review]

**Pull request merged**
