### PR TITLE
fix: improve handling terminated and unschedulable pods

### LINKED ISSUE #1593: Cluster is stuck in fail-over state after a node termination
### Overview

On GKE (possibly other services), the cluster is forever stuck in a fail-over state after a node where a database pod is scheduled is preempted. During this condition, the pods exist in a `Completed` / `Terminated` state and the reconciliation loop doesn't recognize this as a pod `Eviction` and keeps waiting for the Pod to come back online.

### Description

We are running a few different database on a GKE cluster and when a given node goes down (most often due to spot instance preemption), the pod is marked as `Completed` and the operator does not recognize that these pods are failed and keeps waiting for this pod to come back. I believe this could be happening because K8s does not recognize that these pods are managed by an external controller and hence marks the pods as `Completed` instead of `Failed`.

While I recognize that it is not a good practice to schedule database to run on pre-emptible nodes, we have many services that mostly perform occasional read-only operations on a database where we mostly prioritize RTO. These are non-critical services where brief downtime is more than acceptable and the underlying data is more or less static. We would also like to re-use a PVC if at-all possible since the database is big and a recovery from a WAL could take a long time.

### Quick Fix

Manually deleting the given pod (while not touching the PVC) causes the operator to re-create the pod and the database comes back online within a few seconds. However, this does require operator intervention.

### Expected Behavior

The operator should recognize that the pod was shut-down, and delete and re-create the pod while re-using the previous PVC. I _think_ the expectation here that the operator behavior is  identical to how `Evicted` pods are handled.

### Logs

<details>
<summary> Operator Log </summary>

```json
{
  "insertId": "i8qv9ac22xnplf2g",
  "jsonPayload": {
    "status": {
      "podIPs": [
        {
          "ip": "[redacted]"
        }
      ],
      "message": "Pod was terminated in response to imminent node shutdown.",
      "conditions": [
        {
          "type": "Initialized",
          "lastTransitionTime": "2023-02-28T02:06:23Z",
          "lastProbeTime": null,
          "status": "True"
        },
        {
          "lastTransitionTime": "2023-02-28T14:33:52Z",
          "type": "Ready",
          "reason": "PodFailed",
          "lastProbeTime": null,
          "status": "False"
        },
        {
          "lastTransitionTime": "2023-02-28T14:33:52Z",
          "status": "False",
          "reason": "PodFailed",
          "lastProbeTime": null,
          "type": "ContainersReady"
        },
        {
          "type": "PodScheduled",
          "lastProbeTime": null,
          "status": "True",
          "lastTransitionTime": "2023-02-28T02:06:11Z"
        }
      ],
      "reason": "Terminated",
      "startTime": "2023-02-28T02:06:11Z",
      "containerStatuses": [
        {
          "state": {
            "terminated": {
              "finishedAt": "2023-02-28T14:33:51Z",
              "exitCode": 0,
              "reason": "Completed",
              "containerID": "containerd://7f6913ec42f5d4d560f6da99d1e8c5ccd3347d34cab84a1299c87791b2632308",
              "startedAt": "2023-02-28T02:06:33Z"
            }
          },
          "name": "postgres",
          "containerID": "containerd://7f6913ec42f5d4d560f6da99d1e8c5ccd3347d34cab84a1299c87791b2632308",
          "started": false,
          "imageID": "ghcr.io/cloudnative-pg/postgresql@sha256:303e84637bd5f9cfffb4454a93be0006106f21fa48dc8404374ac7003c5b96e1",
          "ready": false,
          "image": "ghcr.io/cloudnative-pg/postgresql:15.1",
          "restartCount": 0,
          "lastState": {}
        }
      ],
      "hostIP": "[redacted]",
      "qosClass": "BestEffort",
      "podIP": "[redacted]",
      "phase": "Failed",
      "initContainerStatuses": [
        {
          "state": {
            "terminated": {
              "exitCode": 0,
              "containerID": "containerd://12229216606763edfa999fe917d8320c4050f9cf64644f2fdef22c2b8a5452a3",
              "finishedAt": "2023-02-28T02:06:23Z",
              "reason": "Completed",
              "startedAt": "2023-02-28T02:06:22Z"
            }
          },
          "containerID": "containerd://12229216606763edfa999fe917d8320c4050f9cf64644f2fdef22c2b8a5452a3",
          "image": "ghcr.io/cloudnative-pg/cloudnative-pg:1.19.0",
          "restartCount": 0,
          "imageID": "ghcr.io/cloudnative-pg/cloudnative-pg@sha256:7b00f732fa5d3ff20fdc2e1ca931cb7eb1612854b42ed8ca4862e749b8f40d17",
          "name": "bootstrap-controller",
          "ready": true,
          "lastState": {}
        }
      ]
    },
    "ts": "2023-02-28T18:04:49Z",
    "reconcileID": "d90496d1-016a-46ab-ace5-1210f4cba91a",
    "controllerKind": "Cluster",
    "Cluster": {
      "namespace": "[redacted]",
      "name": "[redacted]-db"
    },
    "namespace": "[redacted]",
    "uuid": "6496c50f-b792-11ed-9b4a-2647bd45b262",
    "controllerGroup": "postgresql.cnpg.io",
    "controller": "cluster",
    "level": "info",
    "pod": "[redacted]-db-4",
    "name": "[redacted]-db",
    "msg": "Ignoring not active Pod during label update"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "manager",
      "cluster_name": "[redacted]",
      "pod_name": "cloudnative-pg-58ff594f87-q9ccc",
      "project_id": "[redacted]",
      "location": "[redacted]",
      "namespace_name": "postgres"
    }
  },
  "timestamp": "2023-02-28T18:04:49.906538224Z",
  "severity": "INFO",
  "labels": {
    "compute.googleapis.com/resource_name": "[redacted]-ac198-95d89dda-gus2",
    "k8s-pod/pod-template-hash": "58ff594f87",
    "k8s-pod/app_kubernetes_io/name": "cloudnative-pg",
    "k8s-pod/app_kubernetes_io/instance": "cloudnative-pg"
  },
  "logName": "projects/[redacted]/logs/stderr",
  "receiveTimestamp": "2023-02-28T18:04:50.210369665Z"
}
```
</details>

<details>
<summary>Pod Yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    cnpg.io/nodeSerial: "4"
    cnpg.io/operatorVersion: 1.19.0
    cnpg.io/podEnvHash: 8768cc9f
    container.seccomp.security.alpha.kubernetes.io/bootstrap-controller: runtime/default
    container.seccomp.security.alpha.kubernetes.io/postgres: runtime/default
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2023-02-28T02:06:11Z"
  labels:
    cnpg.io/cluster: ${db.name}
    cnpg.io/instanceName: ${db.name}-4
    cnpg.io/podRole: instance
    postgresql: ${db.name}
    role: primary
  name: ${db.name}-4
  namespace: ${db.namespace}
  ownerReferences:
  - apiVersion: postgresql.cnpg.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: ${db.name}
    uid: ae61d547-1ed5-42c3-852f-8c70d264ff2b
  resourceVersion: "55152177"
  uid: 59d25d02-6712-4dec-aa33-ffd5748e03dc
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: cnpg.io/cluster
              operator: In
              values:
              - ${db.name}
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - command:
    - /controller/manager
    - instance
    - run
    - --log-level=info
    env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POD_NAME
      value: ${db.name}-4
    - name: NAMESPACE
      value: ${db.namespace}
    - name: CLUSTER_NAME
      value: ${db.name}
    - name: PGPORT
      value: "5432"
    - name: PGHOST
      value: /controller/run
    image: ghcr.io/cloudnative-pg/postgresql:15.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: postgres
    ports:
    - containerPort: 5432
      name: postgresql
      protocol: TCP
    - containerPort: 9187
      name: metrics
      protocol: TCP
    - containerPort: 8000
      name: status
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata
    - mountPath: /run
      name: scratch-data
    - mountPath: /controller
      name: scratch-data
    - mountPath: /dev/shm
      name: shm
    - mountPath: /etc/superuser-secret
      name: superuser-secret
    - mountPath: /etc/app-secret
      name: app-secret
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: [redacted]
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: ${db.name}-4
  initContainers:
  - command:
    - /manager
    - bootstrap
    - /controller/manager
    - --log-level=info
    image: ghcr.io/cloudnative-pg/cloudnative-pg:1.19.0
    imagePullPolicy: IfNotPresent
    name: bootstrap-controller
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata
    - mountPath: /run
      name: scratch-data
    - mountPath: /controller
      name: scratch-data
    - mountPath: /dev/shm
      name: shm
    - mountPath: /etc/superuser-secret
      name: superuser-secret
    - mountPath: /etc/app-secret
      name: app-secret
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: [redacted]
      readOnly: true
  nodeName: [redacted]
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 26
    runAsGroup: 26
    runAsNonRoot: true
    runAsUser: 26
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: ${db.name}
  serviceAccountName: ${db.name}
  subdomain: ${db.name}-any
  terminationGracePeriodSeconds: 15
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: pgdata
    persistentVolumeClaim:
      claimName: ${db.name}-4
  - emptyDir: {}
    name: scratch-data
  - emptyDir:
      medium: Memory
    name: shm
  - name: superuser-secret
    secret:
      defaultMode: 420
      secretName: ${db.name}-superuser
  - name: app-secret
    secret:
      defaultMode: 420
      secretName: ${db.name}-app
  - name: [redacted]
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-28T02:06:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-02-28T14:33:52Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-02-28T14:33:52Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-02-28T02:06:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://7f6913ec42f5d4d560f6da99d1e8c5ccd3347d34cab84a1299c87791b2632308
    image: ghcr.io/cloudnative-pg/postgresql:15.1
    imageID: ghcr.io/cloudnative-pg/postgresql@sha256:303e84637bd5f9cfffb4454a93be0006106f21fa48dc8404374ac7003c5b96e1
    lastState: {}
    name: postgres
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://7f6913ec42f5d4d560f6da99d1e8c5ccd3347d34cab84a1299c87791b2632308
        exitCode: 0
        finishedAt: "2023-02-28T14:33:51Z"
        reason: Completed
        startedAt: "2023-02-28T02:06:33Z"
  hostIP: [redacted]
  initContainerStatuses:
  - containerID: containerd://12229216606763edfa999fe917d8320c4050f9cf64644f2fdef22c2b8a5452a3
    image: ghcr.io/cloudnative-pg/cloudnative-pg:1.19.0
    imageID: ghcr.io/cloudnative-pg/cloudnative-pg@sha256:7b00f732fa5d3ff20fdc2e1ca931cb7eb1612854b42ed8ca4862e749b8f40d17
    lastState: {}
    name: bootstrap-controller
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://12229216606763edfa999fe917d8320c4050f9cf64644f2fdef22c2b8a5452a3
        exitCode: 0
        finishedAt: "2023-02-28T02:06:23Z"
        reason: Completed
        startedAt: "2023-02-28T02:06:22Z"
  message: Pod was terminated in response to imminent node shutdown.
  phase: Failed
  podIP: [redacted]
  podIPs:
  - ip: [redacted]
  qosClass: BestEffort
  reason: Terminated
  startTime: "2023-02-28T02:06:11Z" 
```
</details>

<details>
<summary>Cluster Configuration</summary>

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${db.name}
  namespace: ${namespace}
spec:
  instances: ${db.replicas}
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  nodeMaintenanceWindow:
    inProgress: true
    reusePVC: true
  stopDelay: 15 # gke node premption is 30s, so we need to stop much before that
  switchoverDelay: 15
  storage:
    size: ${db.size}
  bootstrap:
    initdb:
      database: ${db.name}
      owner: ${db.user}
```
</details>

### LINKED ISSUE #1946: [ Medium Prio] Pods stuck in taint toleration after node restart
In some obscure custom cases, such as single-node TrueNAS SCALE clusters, the cluster adds a taint to the node on reboot, which gets removed after all bootup procedure are finished.

This, obviously means the pods cannot be scheduled till after the taints are removed.
However the pods don't automatically get recreated after the taints are removed from the node. Leading to the cnpg pods never restarting.

Dirty solution:
- Recreate after 5 minutes if pods get stuck in taint-toleration state

Clean solution:
- Check when there is a schedulable node available, then recreate pods

---
Medium prio, due to completely bricking cnpg in some cases on singlenode clusters.

### PR DESCRIPTION
**Pull request by armru**
Closes #1946 and #1593

### CODE REVIEW

**Comment by armru** [comment]
@Ornias1993 Sadly the proposed fix in this PR isn't good enough given that creates a programmatic fail in the E2E test suite.
I will try to investigate further when I have time

**Comment by Ornias1993** [comment]
> @Ornias1993 Sadly the proposed fix in this PR isn't good enough given that creates a programmatic fail in the E2E test suite. I will try to investigate further when I have time

Edited to make clear it's just a global design review.

**Comment by mnencia** [comment]
Full E2E run running in EDB fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9842619062

**Comment by mnencia** [comment]
Full E2E tests running on EDB fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/9857999815

**Review by mnencia — APPROVED** [review]

**Review by leonardoce — APPROVED** [review]

**Pull request merged**
