### PR TITLE
refactor: move barman-cloud support to a separate go module

### PR DESCRIPTION
**Pull request by armru**

### CODE REVIEW

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10789105050

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10791714941

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10796321607

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10815239059

**Comment by leonardoce** [comment]
Full green E2e

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10833565731

**Review by leonardoce — APPROVED** [review]

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10886685414

**Comment by leonardoce** [comment]
E2e were green

**Comment by leonardoce** [comment]
E2e: https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/10906322361

**Review by fcanovai — APPROVED** [review]

**Pull request merged**
