### PR TITLE
feat: allow configuration of certificate duration and expiring check time

### PR DESCRIPTION
**Pull request by zekiyeaydemir**
Allowed the configuration of certificationDuration and expiringCheckThreshold parameters.

Closes: #1691

### CODE REVIEW

**Comment by leonardoce** [comment]
Hi @zekiyeaydemir. We want to merge this in the next release.
Can you please test what happens when you set an incorrect value for `CERTIFICATE_DURATION,` for example, a string instead of a number? We need to be sure we'll have an understandable error message.
Thanks!

**Review by sxd — APPROVED** [review]

**Comment by litaocdl** [comment]
> Hi @zekiyeaydemir. We want to merge this in the next release. Can you please test what happens when you set an incorrect value for `CERTIFICATE_DURATION,` for example, a string instead of a number? We need to be sure we'll have an understandable error message. Thanks!

if the invalid value is set for cetification duration or threhold, default will be used  and info msg will reports in operator log

"Skipping invalid integer value parsing configuration","field":"CertificateDuration","value":"100s"

**Review by litaocdl — APPROVED** [review]

**Pull request merged**
