### PR TITLE
feat(probes): enable customization of startup, liveness, and readiness probes

### LINKED ISSUE #4852: [Feature]: Make pod liveness/readiness probes timeout configurable
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Current databaze pods have 5 seconds timeout to liveness/readiness probes and this timeout is hardcoded in `pkg/specs/pods.go`. It would be nice, if this could be configurable. In our setup, we need timeout about 20 seconds, it seems that DNS is involved in the probe and if DNS reply is lost, the Pod is restarted. With increased timeout, all is running just fine. I understand, it should not be default, but configurable.

### Describe the solution you'd like

Add new field to cluster spec so that Pod probes timeout can be changed. 

### Describe alternatives you've considered

I do not know about alternative as the timeout is currently hardcoded.

### Additional context

_No response_

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by leonardoce**
This patch enables users to customize the default behavior of readiness, liveness, and startup probes implemented by CloudNativePG by introducing the `.spec.probes` section.

Users are responsible for ensuring that any custom probe settings align with the operational requirements of the cluster to avoid unintended disruptions.

Special thanks to @bentastic27 for the contribution that inspired this improvement.

Closes: #4852

### CODE REVIEW

**Comment by leonardoce** [comment]
E2e: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/12157706881

**Review by mnencia — APPROVED** [review]

**Comment by leonardoce** [comment]
The E2e tests are green!

**Review by gbartolini — APPROVED** [review]

**Comment by gbartolini** [comment]
This patch should be backported.

**Review by bentastic27 — APPROVED** [review]

**Pull request merged**
