### PR TITLE
fix: using right tag for UBI8 image during e2e

### LINKED ISSUE #4254: [Bug]: improper tag on UBI8 image in continuous-delivery workflow
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/8610113987/job/23595130675#step:8:89

this job based on the PR https://github.com/cloudnative-pg/cloudnative-pg/pull/4151#issuecomment-2044107282 built the UBI8 image with `main-ubi8` tag

we have already fixed a similar issue in #2395

### Cluster resource

```shell
None
```

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by YanniHu1996**
Closes #4254

### CODE REVIEW

**Comment by YanniHu1996** [comment]
the e2e result from the fork 
https://github.com/YanniHu1996/cloudnative-pg/actions/runs/8625192217/job/23641398469#step:8:87

**Review by sxd — APPROVED** [review]

**Review by NiccoloFei — APPROVED** [review]

**Pull request merged**
