### PR TITLE
test: fix backup and restore e2e test case failure

### LINKED ISSUE #4145: [Bug]: backup and restore, upgading test case is partial failure
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.22.2

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

test case partially failure 

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by litaocdl**
Closes #4145

### CODE REVIEW

**Comment by litaocdl** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8353927528

**Review by YanniHu1996 — APPROVED** [review]

**Comment by litaocdl** [comment]
full run of all cases https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8354545998

**Comment by litaocdl** [comment]
use random serverName: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8355198200

**Comment by litaocdl** [comment]
The above run has invalid label filte, re-run the workflow with a full run
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8356151313

**Review by armru — APPROVED** [review]

**Comment by litaocdl** [comment]
all green for a full run except one backup not start, that one probably missing a checkpoint on primary https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8367596179

**Review by YanniHu1996 — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Pull request merged**
