### PR TITLE
fix: avoid two patch in one reconcile loop

### LINKED ISSUE #335: avoid two patch in one reconcile loop
This is regrading to the cluster condition migration code, trying to avoid spec and status patch in one reconcile loop

### PR DESCRIPTION
**Pull request by litaocdl**
Avoid race condition if two patch is applied in one reconcile loop

Closes #335 

Signed-off-by: Tao Li <tao.li@enterprisedb.com>

### CODE REVIEW

**Review by mnencia — APPROVED** [review]

**Review by phisco — APPROVED** [review]

**Review by phisco — CHANGES_REQUESTED** [review]
All the E2E are failing

**Comment by litaocdl** [comment]
@phisco yes,yes, you are right. if the original cluster has no condition. the 
```
if !reflect.DeepEqual(cluster.Status.Conditions, conditions)
```
will still be true and update status will happen but seems not trigger new reconcile (because status is not changed ?).  but we stop the current reconcile loop. I added one condition to check if original cluster condition is zero or not.

**Comment by litaocdl** [comment]
e2e pass.

**Review by mnencia — APPROVED** [review]

**Review by phisco — APPROVED** [review]

**Pull request merged**
