### PR TITLE
chore: update kustomization files to use Kustomize v5

### LINKED ISSUE #2283: Update Kustomization files to be compatible with Kustomize v5
Change the scaffolding Kustomization files to make them compatible with v5.

### PR DESCRIPTION
**Pull request by cschp**
Closes #2283 

Testing: tested generated kustomize from before and after the changes to see the diff and to check if the sha's match which they usually do

testing in comments below

How:
k5r script used on each of the kustomization.yaml files
script listed in comments

### CODE REVIEW

**Comment by cschp** [comment]
``casey in ~/cloudnative-pg/config/certmanager on main λ k5r

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels

To convert vars -> replacements, run the command kustomize edit fix --vars

WARNING: Converting vars to replacements will potentially overwrite many resource files
and the resulting files may not produce the same output when kustomize build is run.
We recommend doing this in a clean git repository where the change is easy to undo.

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
vars -> replacements

sha before the update 88c63d67a56ec2a3cc0e1d5bfe77c2886902c28a9a86a2b0539e649908ff34ae
sha after the update 88c63d67a56ec2a3cc0e1d5bfe77c2886902c28a9a86a2b0539e649908ff34ae
shas match before and after kustomize updates made.
The diff of the files before and after update is
There is no diff between before the kustomize changes and after``

**Comment by cschp** [comment]
`casey in ~/cloudnative-pg/config/crd on main ● λ k5r

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels

To convert vars -> replacements, run the command kustomize edit fix --vars

WARNING: Converting vars to replacements will potentially overwrite many resource files
and the resulting files may not produce the same output when kustomize build is run.
We recommend doing this in a clean git repository where the change is easy to undo.

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
vars -> replacements

sha before the update 7ceeb2023cebe194661d9f632a3b73870e2349bffd77f075092a29b46d2ff352
sha after the update 7ceeb2023cebe194661d9f632a3b73870e2349bffd77f075092a29b46d2ff352
shas match before and after kustomize updates made.
The diff of the files before and after update is
There is no diff between before the kustomize changes and after
casey in ~/cloudnative-pg/config/crd on main ● λ`

**Comment by cschp** [comment]
``casey in ~/cloudnative-pg/config/default on main ● λ k5r

Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels

To convert vars -> replacements, run the command kustomize edit fix --vars

WARNING: Converting vars to replacements will potentially overwrite many resource files
and the resulting files may not produce the same output when kustomize build is run.
We recommend doing this in a clean git repository where the change is easy to undo.

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
vars -> replacements

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
sha before the update 282fdf0c36be05fff0a389f1a138fea446036c925aaeabcb4294c273c3883b7d
sha after the update 282fdf0c36be05fff0a389f1a138fea446036c925aaeabcb4294c273c3883b7d
shas match before and after kustomize updates made.
The diff of the files before and after update is
There is no diff between before the kustomize changes and after
casey in ~/cloudnative-pg/config/default on main ● λ``

**Comment by cschp** [comment]
``casey in ~/cloudnative-pg/config/manager on main ● λ k5r

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels

To convert vars -> replacements, run the command kustomize edit fix --vars

WARNING: Converting vars to replacements will potentially overwrite many resource files
and the resulting files may not produce the same output when kustomize build is run.
We recommend doing this in a clean git repository where the change is easy to undo.

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
Error: error with manager.yaml: cannot convert all vars to replacements; $(OPERATOR_DEPLOYMENT_NAME) is not delimited
Usage:
kustomize edit fix [flags]

Examples:

# Fix the missing and deprecated fields in kustomization file
kustomize edit fix
Flags:
-h, --help help for fix
--vars If specified, kustomize will attempt to convert vars to replacements.
We recommend doing this in a clean git repository where the change is easy to undo.

Global Flags:
--stack-trace print a stack-trace on error

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
2023/06/12 16:21:54 well-defined vars that were never replaced: OPERATOR_IMAGE_NAME

sha before the update 9a03334f3ba2d6917b1873ac9248b3ce8c32072d0bfd1f3bcca6f763f4d3d40f
sha after the update 85b4283a70d86678871dd2e3995f3792f72fd5c3566d21b3c836b3947e8e3b82
shas don't match.
The diff of the files before and after update is 421c421 < value: OPERATOR_IMAGE_NAME_PLACEHOLDER --- > value: controller:latest
There is a diff
casey in ~/cloudnative-pg/config/manager on main ● λ``

**Comment by cschp** [comment]
``casey in ~/cloudnative-pg/config/manifests on main ● λ k5r

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
2023/06/12 16:22:20 well-defined vars that were never replaced: OPERATOR_IMAGE_NAME

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
2023/06/12 16:22:20 well-defined vars that were never replaced: OPERATOR_IMAGE_NAME

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels

To convert vars -> replacements, run the command kustomize edit fix --vars

WARNING: Converting vars to replacements will potentially overwrite many resource files
and the resulting files may not produce the same output when kustomize build is run.
We recommend doing this in a clean git repository where the change is easy to undo.

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
2023/06/12 16:22:21 well-defined vars that were never replaced: OPERATOR_IMAGE_NAME

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
2023/06/12 16:22:21 well-defined vars that were never replaced: OPERATOR_IMAGE_NAME

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
vars -> replacements

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
2023/06/12 16:22:21 well-defined vars that were never replaced: OPERATOR_IMAGE_NAME

Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
2023/06/12 16:22:21 well-defined vars that were never replaced: OPERATOR_IMAGE_NAME

sha before the update 502dd36282dd37d6539aaf9cde6e7ba350cc34c70a87c01dd48afebf0fad7172
sha after the update 502dd36282dd37d6539aaf9cde6e7ba350cc34c70a87c01dd48afebf0fad7172
shas match before and after kustomize updates made.
The diff of the files before and after update is
There is no diff between before the kustomize changes and after
casey in ~/cloudnative-pg/config/manifests on main ● λ``

**Comment by cschp** [comment]
``casey in ~/cloudnative-pg/config/prometheus on main ● λ k5r

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels

To convert vars -> replacements, run the command kustomize edit fix --vars

WARNING: Converting vars to replacements will potentially overwrite many resource files
and the resulting files may not produce the same output when kustomize build is run.
We recommend doing this in a clean git repository where the change is easy to undo.

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
vars -> replacements

sha before the update 2006d89ce9551b25d3dbc48db05a82d105bde69748df7705d12054345ca67799
sha after the update 2006d89ce9551b25d3dbc48db05a82d105bde69748df7705d12054345ca67799
shas match before and after kustomize updates made.
chore(UPM-20822): updating kustomization.yaml files to use kustomize 5
The diff of the files before and after update is
There is no diff between before the kustomize changes and after
casey in ~/cloudnative-pg/config/prometheus on main ● λ``

**Comment by cschp** [comment]
``casey in ~/cloudnative-pg/config/webhook on main ● λ k5r

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels

To convert vars -> replacements, run the command kustomize edit fix --vars

WARNING: Converting vars to replacements will potentially overwrite many resource files
and the resulting files may not produce the same output when kustomize build is run.
We recommend doing this in a clean git repository where the change is easy to undo.

Fixed fields:
patchesJson6902 -> patches
patchesStrategicMerge -> patches
commonLabels -> labels
vars -> replacements

sha before the update 88c92692c7ef50289e241a71011746003d8bbeb6beacf8605c415ae3153bbaed
sha after the update 88c92692c7ef50289e241a71011746003d8bbeb6beacf8605c415ae3153bbaed
shas match before and after kustomize updates made.
The diff of the files before and after update is
There is no diff between before the kustomize changes and after
casey in ~/cloudnative-pg/config/webhook on main ● λ``

**Comment by cschp** [comment]
casey in ~ λ cat .local/bin/k5r
#!/bin/sh

kustomize build . > tacos_base.txt
kustomize edit fix
kustomize edit fix --vars
kustomize build . > tacos.txt
sha1=$(sha256sum tacos_base.txt |  head -c 64)
echo "\nsha before the update" $sha1
sha2=$(sha256sum tacos.txt |  head -c 64)
echo "sha after the update " $sha2
if [[ "$sha1" == "$sha2" ]]
then
echo "shas match before and after kustomize updates made."
else
echo "shas don't match."
fi
DIFF=$(diff tacos.txt tacos_base.txt)
echo "The diff of the files before and after update is " $DIFF
if [ "$DIFF" != "" ]
then
    echo "There is a diff"
else
    echo "There is no diff between before the kustomize changes and after"
fi
casey in ~ λ

**Comment by sxd** [comment]
Hi @cschp there's a lot of changes on this PR that doesn't make sense, can you rebase and work in a proper PR to fix this? you're doing changes where nothing should be changed.

Also the commit messages aren't following the used standard here

Regards!

**Pull request closed without merging**
