### PR TITLE
feat: stricter readiness probe for replicas

### PR DESCRIPTION
**Pull request by leonardoce**
Enhance the readiness probe functionality to avoid marking streaming replicas as ready before establishing a successful connection with the corresponding primary.

This improvement allows users to quickly identify and address inconsistencies between replicas and primary instances.

# Release Notes

The readiness probe now fails for streaming replicas that were never connected to the primary instance, allowing incoherent replicas to be discovered promptly.

### CODE REVIEW

**Comment by leonardoce** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10182207522

**Comment by leonardoce** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10183490630

**Comment by gbartolini** [comment]
I think this is a fix, and I vote for inclusion in 1.24 directly. We should not declare a replica ready if it's never been able to establish a replication connection.

**Review by jsilvela — APPROVED** [review]

**Review by armru — APPROVED** [review]

**Review by sxd — APPROVED** [review]

**Review by sxd — APPROVED** [review]

**Pull request merged**
