### PR TITLE
feat: allow configuring log-level TCP parameters for PgBouncer

### PR DESCRIPTION
**Pull request by dspeck1**
Adding TCP parameters to allowed configurable parameters on webhook per discussion topic.  https://github.com/cloudnative-pg/cloudnative-pg/discussions/563  Please let me know if anything needs changed or added.

### CODE REVIEW

**Comment by leonardoce** [comment]
Hi @dspeck1! Can you please sign-off your commit as per the documentation here https://github.com/cloudnative-pg/cloudnative-pg/blob/main/contribute/README.md? 

Can you please create an issue too and reference it from your PR? 

Thank you!

**Comment by dspeck1** [comment]
Updated from discussion to issue.  Bouncer TCP settings #604

**Comment by dspeck1** [comment]
Assigned to issue and signed in commit message. @leonardoce - please let me know if you need anything else.

**Review by leonardoce — APPROVED** [review]

**Review by sxd — APPROVED** [review]

**Comment by leonardoce** [comment]
@dspeck1 I just changed a bit the commit message, rebased it on the latest main and used your GitHub nickname into the sign-off phrase, as DCO required.

E2e tests are running 🤞

**Comment by leonardoce** [comment]
I tested it manually too and everything is fine

**Pull request merged**
