### PR TITLE
fix: reload certificates on configuration update

### LINKED ISSUE #2276: Error Certificate signed by unknown authority log messages
We are seeing these log message from our pods:

```
{
"level":"info",
"ts":"2023-06-14T02:39:45Z",
"logger":"Replicator",
"msg":"synchronizing replication slots",
"logging_pod":"pg-database-2",
"err":"getting replication slot status from primary: failed to connect to `host=pg-database-rw user=streaming_replica database=postgres`: tls error (x509: certificate signed by unknown authority)"
}

{
"level":"info",
"ts":"2023-06-14T02:39:45Z",
"logger":"postgres",
"msg":"record",
"logging_pod":"pg-database-1",
"record":{
	"log_time":"2023-06-14 02:39:45.218 UTC",
	"process_id":"1686086",
	"connection_from":"10.16.17.122:53842",
	"session_id":"64892871.19ba46",
	"session_line_num":"1",
	"session_start_time":"2023-06-14 02:39:45 UTC",
	"transaction_id":"0",
	"error_severity":"LOG",
	"sql_state_code":"XX000",
	"message":"could not accept SSL connection: No error information",
	"backend_type":"not initialized",
	"query_id":"0"
	}
}
```

When i run `kubectl cnpg status pg-database`

I get the following:
```
Certificates Status
Certificate Name         Expiration Date                Days Left Until Expiration
----------------         ---------------                --------------------------
pg-database-ca           2023-09-01 21:46:15 +0000 UTC  79.79
pg-database-replication  2023-09-01 21:46:15 +0000 UTC  79.79
pg-database-server       2023-09-01 21:46:15 +0000 UTC  79.79
```

What is the cause of this, and how do we resolve it ?

### PR DESCRIPTION
**Pull request by ecksun**
After a certificate expires the replicator will start printing error-logs:

```json
{
  "level": "info",
  "ts": "2024-01-16T11:30:58Z",
  "logger": "Replicator",
  "msg": "synchronizing replication slots",
  "logging_pod": "edge-ha-db-cnpg-3",
  "err": "getting replication slot status from primary: failed to connect to `host=edge-ha-db-cnpg-rw user=streaming_replica database=postgres`: failed to write startup message (write failed: x509: certificate has expired or is not yet valid: current time 2024-01-16T11:30:58Z is after 2024-01-16T11:30:45Z)"
}
```

This happens because certificates were read from disk the first time the connection was used and subsequently cached in the pool.

The errors are accompanied by the following error from the leader:

```json
{
  "level": "info",
  "ts": "2024-01-16T13:22:28Z",
  "logger": "postgres",
  "msg": "record",
  "logging_pod": "edge-ha-db-cnpg-1",
  "record": {
    "log_time": "2024-01-16 13:22:28.263 UTC",
    "process_id": "12756",
    "connection_from": "10.244.0.97:60832",
    "session_id": "65a68314.31d4",
    "session_line_num": "1",
    "session_start_time": "2024-01-16 13:22:28 UTC",
    "transaction_id": "0",
    "error_severity": "LOG",
    "sql_state_code": "08P01",
    "message": "could not accept SSL connection: sslv3 alert bad certificate"
  }
}
```

If in this scenario another primary is promoted the replica will print the following error:

```json
{
  "level": "info",
  "ts": "2024-01-16T13:32:59Z",
  "logger": "Replicator",
  "msg": "synchronizing replication slots",
  "logging_pod": "edge-ha-db-cnpg-2",
  "err": "getting replication slot status from primary: failed to connect to `host=edge-ha-db-cnpg-rw user=streaming_replica database=postgres`: failed to write startup message (write failed: x509: certificate signed by unknown authority)"
}
```

By stopping all connections on a configuration change the certificates will be read from disk again the next time a connection is needed.

# meta

- I'm not sure how to add a test-case for this and would love some directions

Closes #2276

### CODE REVIEW

**Comment by clrxbl** [comment]
Just encountered this issue on our production databases causing them to run out of disk space and crash as WAL files weren't being deleted.

**Comment by karlbohlmark** [comment]
I have also been hit by this issue. Is there any way to get some triage of this so we know if it is planned? We need to decide if we should fork or wait for a release.

**Comment by clrxbl** [comment]
> I have also been hit by this issue. Is there any way to get some triage of this so we know if it is planned? We need to decide if we should fork or wait for a release.

I should mention that I'd probably suggest setting https://postgresqlco.nf/doc/en/param/max_slot_wal_keep_size/ to a reasonable value as it will at least make sure only your replicas are affected without eating up all disk space within your PersistentVolume making recovery easier at a later time.

**Comment by karlbohlmark** [comment]
Yes, thanks. Unfortunately we have yet to upgrade to PostgreSQL 13, so that setting isn't available to us, but we are planning that change now.

**Comment by mnencia** [comment]
@sxd can you please review this pr as it falls in your area of expertise?

**Comment by Foosvald** [comment]
@mnencia @sxd Any updates on this? We're still suffering from this and don't know if we should fork and build CNPG with the fix for the time being or wait until this is merged...

**Comment by sxd** [comment]
@Foosvald yes, the next release will come with a fix, this is on the queue

**Review by mnencia — APPROVED** [review]

**Review by litaocdl — APPROVED** [review]

**Pull request merged**
