### PR TITLE
test(e2e): more precise wildcard to match wal file

### PR DESCRIPTION
**Pull request by YanniHu1996**
close: #4267

### CODE REVIEW

**Comment by YanniHu1996** [comment]
the e2e from fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8682774868

**Comment by litaocdl** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8682774868 e2e is run here

**Review by litaocdl — APPROVED** [review]

**Review by sxd — APPROVED** [review]

**Comment by sxd** [comment]
/ok-to-merge test failed but not related to the touch that was touched

**Pull request merged**
