### PR TITLE
fix(prometheus): add the cnpg_cluster label

### PR DESCRIPTION
**Pull request by achanda**
Closes: #2501

This PR renames the cluster label in prometheus to cnpg_cluster since that label is commonly used to refer to the k8s cluster. This is a breaking change.

### CODE REVIEW

**Comment by achanda** [comment]
I wonder if we should do this in two separate releases: the first one adding the extra label and the second one removing the deprecated label. Thoughts?

**Comment by sjentzsch** [comment]
Small notes from my side (non-maintainer):

We might also want to apply same changes to `grafana-configmap.yaml` as it's the `grafana-dashboard.json` wrapped inside a configmap (would be best of course to not have this redundancy anymore ...)

Instead of adding both labels at the same time as an intermediate step, we could also make us of (optional) relabeling at `PodMonitor` level (https://cloudnative-pg.io/documentation/1.20/monitoring/#prometheus-operator-example), so e.g. 

```
  podMetricsEndpoints:
  - port: metrics
    relabelings:
    - sourceLabels: [cnpg_cluster]
      targetLabel: cluster
      action: replace
```

to rewrite `cnpg_cluster` back to `cluster`, if people want it. But thinking about it twice, as not everyone might use PodMonitor, probably exposing both metrics at the same time might indeed be a thing. Or, as we might also not want to maintain both dashboard types at the same time, just do the breaking change.

**Comment by gbartolini** [comment]
@achanda can you please try again by following the suggestions that @phisco gave in the original issue #2501? thanks

**Comment by achanda** [comment]
Hi @gbartolini @sxd does this one look good now? Please let me know if this PR needs anything else.

**Review by gbartolini — APPROVED** [review]

**Comment by sxd** [comment]
Hi @achanda 

This PR it's actually not working I'm going to throw the observability testing here but you can get the error here:
```
{"level":"info","ts":"2023-09-21T23:30:23Z","msg":"Query with the same name already found. Overwriting the existing one.","logging_pod":"cluster-example-1","queryName":"pg_database"}
{"level":"info","ts":"2023-09-21T23:30:23Z","msg":"Query with the same name already found. Overwriting the existing one.","logging_pod":"cluster-example-1","queryName":"pg_database"}
panic: inconsistent label cardinality: expected 2 label values but got 1 in []string{"cluster-example"}

goroutine 321 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).WithLabelValues(...)
	/home/zeus/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/gauge.go:238
github.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver/metricserver.(*Exporter).collectPgMetrics(0xc0002964b0, 0xc00068f6c8?)
	pkg/management/postgres/webserver/metricserver/pg_collector.go:361 +0xff4
github.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/webserver/metricserver.(*Exporter).Collect(0xc0002964b0, 0xc00068f760?)
	pkg/management/postgres/webserver/metricserver/pg_collector.go:298 +0x2c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/home/zeus/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/registry.go:455 +0x102
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 285
	/home/zeus/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/registry.go:547 +0xbab
```

**Comment by sxd** [comment]
There's a new PR

**Pull request closed without merging**
