### PR TITLE
fix: execute reconciliation of backups unless they're marked as `failed` or `completed`

### LINKED ISSUE #2467: Backup retry logic is not working unless the backup is still in pending state
The Backup resource reconciliation cycle [exits at the start](https://github.com/cloudnative-pg/cloudnative-pg/blob/8e7cf98be8d664593e5637104d6e361564909c06/controllers/backup_controller.go#L95) when the backup Phase is not `pending`.

The code [checking for deleted pods](https://github.com/cloudnative-pg/cloudnative-pg/blob/8e7cf98be8d664593e5637104d6e361564909c06/controllers/backup_controller.go#L158) is after that point, so the operator will never retry a `running` backup.

### PR DESCRIPTION
**Pull request by armru**
Closes #2467

### CODE REVIEW

**Comment by mnencia** [comment]
/ok-to-merge all tests passed beside one failing for resource exaustion

**Review by mnencia — APPROVED** [review]

**Review by NiccoloFei — APPROVED** [review]

**Pull request merged**
