### PR TITLE
ci: Nightly build kubectl plugin in case it breaks release 

### LINKED ISSUE #710: Nightly build of the kubectl plugin in case it breaks release

### PR DESCRIPTION
**Pull request by hh24k**
Closes #710 

Signed-off-by: Hai He <hai.he@enterprisedb.com>

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Comment by litaocdl** [comment]
The above /test command failed is as expected, because slash command for ci workflow will use the merged workflow files, but for [chatops-receiver.yml](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/.github/workflows/chatops-receiver.yml) and [chatops-dispatcher.yml](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/.github/workflows/chatops-dispatcher.yml), it is using the files on `main` branch.

**Pull request merged**
