### PR TITLE
fix: defaults to `app` owner and database during recovery

### LINKED ISSUE #2425: Controller doesn't restore app secret when recovering from backup by name
### Steps to Reproduce
Restore a cluster as recommended in the docs: https://cloudnative-pg.io/documentation/1.20/bootstrap/#recovery-from-a-backup-object
  ```yaml
  apiVersion: postgresql.cnpg.io/v1
  kind: Cluster
  metadata:
    name: cluster-example-initdb
  spec:
    instances: 3

    superuserSecret:
      name: superuser-secret

    bootstrap:
      recovery:
        backup:
          name: backup-example

    storage:
      size: 1Gi
  ```

### Expected Results
* The `-app` secret is created

### Additional Context
Setting `owner` / `database` will fix it:
```yaml
  bootstrap:
    recovery:
      backup:
        name: backup-example
      database: app
      owner: app
```

That's the requirement in `ShouldRecoveryCreateApplicationDatabase`:
https://github.com/cloudnative-pg/cloudnative-pg/blob/c1c50d99aeef5df09e0c99fb4c78e192bfa796e9/api/v1/cluster_types.go#L2297

That's what's used to determine if the app secret should be created:
https://github.com/cloudnative-pg/cloudnative-pg/blob/c1c50d99aeef5df09e0c99fb4c78e192bfa796e9/api/v1/cluster_types.go#L2188-L2192

Called during reconciliation:
https://github.com/cloudnative-pg/cloudnative-pg/blob/c1c50d99aeef5df09e0c99fb4c78e192bfa796e9/controllers/cluster_create.go#L217

### PR DESCRIPTION
**Pull request by armru**
Closes #2425

### CODE REVIEW

**Comment by gbartolini** [comment]
IMO this is should be presented as a bug fix.

**Review by leonardoce — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Pull request merged**
