### PR TITLE
fix: support infinity in Declarative Roles

### LINKED ISSUE #2354: Managed role created but still in pending state
I've added a managed role to a cluster:

```yaml
  managed:
    roles:
      - name: pgdrone_as
        ensure: present
        login: True
        superuser: False
        passwordSecret:
          name: drone-server-postgres-autoscaler
```

The role was created successfully on the cluster:

```
kubectl cnpg -n drone-github psql drone-server-postgres
psql (14.8 (Debian 14.8-1.pgdg110+1))
Type "help" for help.

postgres=# \du
                                       List of roles
     Role name     |                         Attributes                         | Member of 
-------------------+------------------------------------------------------------+-----------
 pgdrone           |                                                            | {}
 pgdrone_as        |                                                            | {}
```

But looking at the cluster status, the new role is still listed as pending:

```
  Managed Roles Status:
    By Status:
      Pending - Reconciliation:
        pgdrone_as
      Reserved:
        streaming_replica
        postgres
    Password Status:
      pgdrone_as:
        Resource Version:  25496087
        Transaction ID:    854
  Phase:                   Cluster in healthy state
```

Besides that, checking the cluster pod logs, it looks like the operator tries to create the role multiple times which is causing some errors:

```
{"level":"error","ts":"2023-06-24T15:26:01Z","logger":"roles_reconciler","msg":"while performing CREATE","logging_pod":"drone-server-postgres-1","role":"pgdrone_as","error":"while trying to CREATE: could not create role pgdrone_as: ERROR: role \"pgdrone_as\" already exists (SQLSTATE 42710) ","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).applyRoleActions.func1\n\tinternal/management/controller/roles/runnable.go:233\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).applyRoleActions\n\tinternal/management/controller/roles/runnable.go:254\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).synchronizeRoles\n\tinternal/management/controller/roles/runnable.go:193\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).reconcile\n\tinternal/management/controller/roles/runnable.go:146\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).Start.func1\n\tinternal/management/controller/roles/runnable.go:103"}
{"level":"error","ts":"2023-06-24T15:26:01Z","logger":"roles_reconciler","msg":"while performing CREATE","logging_pod":"drone-server-postgres-1","role":"pgdrone_as","error":"while trying to CREATE: could not create role pgdrone_as: ERROR: role \"pgdrone_as\" already exists (SQLSTATE 42710) ","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).applyRoleActions.func1\n\tinternal/management/controller/roles/runnable.go:233\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).applyRoleActions\n\tinternal/management/controller/roles/runnable.go:254\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).synchronizeRoles\n\tinternal/management/controller/roles/runnable.go:193\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).reconcile\n\tinternal/management/controller/roles/runnable.go:146\ngithub.com/cloudnative-pg/cloudnative-pg/internal/management/controller/roles.(*RoleSynchronizer).Start.func1\n\tinternal/management/controller/roles/runnable.go:103"}
```

Am I doing something wrong, or is this a bug?

### PR DESCRIPTION
**Pull request by jsilvela**
`infinity`, and `-infinity` are valid values for VALID UNTIL, but were not
being read properly by the declarative role manager.
This patch adds support for reading and reconciling PostgreSQL roles
with these values for password expiry.

Closes #2354

### CODE REVIEW

**Review by sxd — APPROVED** [review]

**Review by jlong49 — APPROVED** [review]

**Comment by gbartolini** [comment]
I am not sure we should add another field for this. I would rather work on the 'Null' semantic for this and, when NULL set it to 'infinity'

**Review by mnencia — APPROVED** [review]

**Comment by jsilvela** [comment]
Fixed the E2E tests, kicked off a quick run (using `smoke` label which includes roles tests)
https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/5413587178

**Comment by jsilvela** [comment]
The run ☝️ finished green, including the managed roles tests.

**Pull request merged**
