### PR TITLE
refactor: moving Azurite setup code to utils.

### PR DESCRIPTION
**Pull request by danishedb**
Closes: #393 
Signed-off-by: Danish Khan <danish.khan@enterprisedb.com>

### CODE REVIEW

**Comment by litaocdl** [comment]
Removed the azurite yaml file and use go to create as it is in utils package.

**Review by litaocdl — APPROVED** [review]

**Review by wadlejitendra — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Pull request merged**
