### PR TITLE
chore: include volume snapshots in cluster status computation

### LINKED ISSUE #2924: Point of recoverability should also consider volume snapshots
At the moment, point of recoverability (`firstRecoverabilityPoint`) in the Cluster's status only considers backups in the object store.

We should ensure that volume snapshots are now taken in the equation. It would be great to add this to 1.21.0 if we can.

### PR DESCRIPTION
**Pull request by jsilvela**
This patch enhances the computation of the first recoverability point
for a cluster by considering volume snapshots in addition to object
store backups.
To ensure no information is lost, it introduces a new field in the
cluster status where the oldest backup available per-method is recorded.
The overall FirstRecoverabilityPoint is computed as the oldest among them.

Closes #2924

### CODE REVIEW

**Comment by jsilvela** [comment]
E2E tests running on shadow repo: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/6666904006

**Review by litaocdl — APPROVED** [review]

**Comment by mnencia** [comment]
E2E tests running on the EDB fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/6929445001

**Comment by mnencia** [comment]
E2E tests running in EDB fork https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/7031008229

**Comment by mnencia** [comment]
/ok-to-merge the E2E executed in the EDB fork are green

**Pull request merged**
