### PR TITLE
test: fix some rough edges of E2E test scripts

### PR DESCRIPTION
**Pull request by mnencia**
Improve the user experience of E2E tests.

* Remove the need to manually define the SnapshotClass in clusters
  created with hack/setup-cluster.sh script
* Fix the configuration of k3d clusters
* Separate the k3d default node version from the kind default node version,
  because often they differ.
* Fix an error hiding log lines longer than 64k in the test output.

Closes: #3871, #3873

### CODE REVIEW

**Review by sxd — APPROVED** [review]

**Comment by gbartolini** [comment]
I was able to easily create a `k3d` cluster and deploy the operator.

```
$ ./hack/setup-cluster.sh -e k3d -r load deploy
Creating k3d cluster pg-operator-e2e-v1-27-1 with version v1.27.1
INFO[0000] Prep: Network
INFO[0000] Created network 'k3d-pg-operator-e2e-v1-27-1'
INFO[0000] Created image volume k3d-pg-operator-e2e-v1-27-1-images
...
storageclass.storage.k8s.io/csi-hostpath-sc annotated
 CSI driver plugin deployment has started. Waiting for the CSI plugin to be ready...
Success: The CSI plugin is deployed and ready.
Done creating k3d cluster pg-operator-e2e-v1-27-1 with version v1.27.1
```

Then:

```
$ k3d cluster list
NAME                      SERVERS   AGENTS   LOADBALANCER
pg-operator-e2e-v1-27-1   1/1       3/3      false
```

Then:

```
$ ./hack/setup-cluster.sh -e k3d -r load deploy
Building operator from current worktree
make: Entering directory '/Users/gabriele.bartolini/prj/cloudnative-pg/cloudnative-pg'
...
make: Leaving directory '/Users/gabriele.bartolini/prj/cloudnative-pg/cloudnative-pg'
Done deploying manifests from current worktree on cluster pg-operator-e2e-v1-27-1
```

And finally able to use it.

Thanks.

**Review by gbartolini — APPROVED** [review]

**Pull request merged**
