### PR TITLE
feat: update Go version from 1.17 to 1.18

### LINKED ISSUE #457: Update to Go 1.18

### PR DESCRIPTION
**Pull request by sxd**
Also, update golangci-lint to version 1.47, which has better support for go 1.18

Closes #457

Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>

### CODE REVIEW

**Comment by mnencia** [comment]
The operator is crashing with this patch, see https://github.com/cloudnative-pg/cloudnative-pg/runs/7464645526?check_suite_focus=true#step:9:34

**Review by mnencia — APPROVED** [review]

**Review by phisco — APPROVED** [review]

**Comment by mnencia** [comment]
We see regressions in the tests. Do not merge until we understand why.

**Comment by sxd** [comment]
With the latest test run now everything is green

**Pull request merged**
