### PR TITLE
chore: add a new way to connect to the clusters from tests

### LINKED ISSUE #5513: [Bug]: Remove the use of psql pod in the tests
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.24.0

### What version of Kubernetes are you using?

1.31

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

Every time we run the tests we create a psql pod that is used just to execute psql commands against the cluster, we should avoid this by using a port-foward locally from the machine running the tests, this will reduce the time to start and finish the tests because creating and destroying this pod take a lot of time

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sxd**
We've been using a pod to use a psql client to connect, this implements
a port-forward that can be used by the tests to connect locally to the
pod clusters removing the need of the psql pod.

Closes #5513

### CODE REVIEW

**Comment by NiccoloFei** [comment]
E2E run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10997846349

**Review by NiccoloFei — APPROVED** [review]

**Review by YanniHu1996 — APPROVED** [review]
LGTM

**Review by fcanovai — APPROVED** [review]

**Pull request merged**
