### PR TITLE
feat: annotation to disable WAL archiving

### PR DESCRIPTION
**Pull request by leonardoce**
Introduce the `cnpg.io/skipWalArchiving` annotation to disable WAL archiving when set to `enabled`.

Closes: #3774

### CODE REVIEW

**Comment by gbartolini** [comment]
I have been able to disable WAL archiving and reduce WAL footprint with the following example:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  annotations:
    cnpg.io/skipWalArchiving: "enabled"
spec:
  instances: 1

  storage:
    size: 1Gi
  postgresql:
    parameters:
      wal_level: minimal
      max_wal_senders: "0"
```

**Review by armru — APPROVED** [review]

**Pull request merged**
