### PR TITLE
chore: update minimum version of Go required

### LINKED ISSUE #3056: Update go semantic version in go mod file
Update the minimum version required to compile packages, since we experienced the error using the go mod vendor spec 1.19:

```
api/v1/backup_types.go:370:47: list.Items[i].CreationTimestamp.Time.Compare undefined (type time.Time has no field or method Compare)
```

See https://go.dev/doc/modules/gomod-ref#go

### PR DESCRIPTION
**Pull request by mbiagetti**
Closes #3056

### CODE REVIEW

**Comment by mnencia** [comment]
This is a good change, but I would delay it until the 1.21 is released.

**Review by leonardoce — APPROVED** [review]

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
Started an E2e test suite on the private EDB repo

**Comment by leonardoce** [comment]
E2e tests are green on the EDB side

**Pull request merged**
