### PR TITLE
feat: Introduce 'smartStopDelay' for managing PG smart shutdown timeout

### PR DESCRIPTION
**Pull request by YanniHu1996**
Closes: #2844

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

**Review by armru — APPROVED** [review]

**Comment by armru** [comment]
Hello, @litaocdl @YanniHu1996. I think we have broken the E2E test because now we are waiting a long time before cutting the connections.

We should fix this issue by keeping the old behaviour in the tests by hard-coding 30 seconds in the fixtures

**Comment by litaocdl** [comment]
now the e2e pass, the failure in ugprade is waiting for cluster ready, but already have two pod ready and the third one with pvc in pending status, which is not with this change.

**Comment by litaocdl** [comment]
run from fork: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/6297393445

**Review by gbartolini — APPROVED** [review]

**Pull request merged**
