### PR TITLE
test: E2E kind env configuration to support volumesnapshot

### LINKED ISSUE #2483: Configure volumesnapshot infrastructure suppport for e2e cloud environment
we need to enhance the E2E test cloud environments (EKS, AKS, and GKE), adding all the components and configurations required to test the Volumes Snapshot support code in our E2E tests.

### PR DESCRIPTION
**Pull request by litaocdl**
This patch contains the configuration for E2E kind environment support 
for VolumeSnapshot. 

Closes #2483

### CODE REVIEW

**Comment by litaocdl** [comment]
test running in cnpg enterprise fork
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/5735209613/job/15542653035

**Comment by litaocdl** [comment]
https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/5736541576

**Review by armru — APPROVED** [review]

**Review by NiccoloFei — APPROVED** [review]

**Pull request merged**
