### PR TITLE
fix: accept provided replication client secret

### LINKED ISSUE #2542: cert-manager cannot be used for replication certs
The [documentation](https://cloudnative-pg.io/documentation/1.20/certificates/) states the you can use cert-manager to provision `clientCASecret` and `replicationTLSSecret`. Example manifests are provided in the docs.

The manifests do not work as the cert-manager generated secret does not contain a `ca.key` entry as it is of type `kubernetes.io/tls`. As a result, cert-manager cannot be used to manage this secret, and I believe the docs are incorrect or a bug exists here.

Version: `1.20.2`

<details>
  <summary>Logs</summary>
  
```json
  
  {
     "level":"error",
     "ts":"2023-08-08T01:56:08Z",
     "msg":"Reconciler error",
     "controller":"cluster",
     "controllerGroup":"postgresql.cnpg.io",
     "controllerKind":"Cluster",
     "Cluster":{
        "name":"api-server-pg",
        "namespace":"api-server"
     },
     "namespace":"api-server",
     "name":"api-server-pg",
     "reconcileID":"5d3d9c1b-d5da-40e7-b2a1-3d352ae0dd19",
     "error":"cannot create Cluster auxiliary objects: generating streaming replication client certificate: missing ca.key secret data",
     "stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"
  }
```
</details>

### PR DESCRIPTION
**Pull request by phisco**
Fixes #2542.

We forgot to properly handle the replication secret passed by the user as we are already doing for all other TLS secrets.

The [example](https://cloudnative-pg.io/documentation/1.21/certificates/#cert-manager-example_1) in the docs now actually works 🎉

### CODE REVIEW

**Review by armru — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Comment by wasd171** [comment]
Thanks for implementing and merging it! Is there a chance of this being released in official Docker images soon? Or should we use `ghcr.io/cloudnative-pg/cloudnative-pg-testing` for the time being?

**Comment by leonardoce** [comment]
The next release will have your fix, too. 👍
I cannot commit to the release date, but is should be near.

**Pull request merged**
