### PR TITLE
feat: support to pass extra options for barman-cloud-backup command

### PR DESCRIPTION
**Pull request by litaocdl**
This patch enables appending extra options to the
`barman-cloud-backup`  command  through a new field in
the cluster CRD.
The options added need to be supported by barman.

Closes:  #3863

### CODE REVIEW

**Comment by litaocdl** [comment]
workflow run here https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/8074851739

**Review by armru — APPROVED** [review]

**Comment by armru** [comment]
I think before merging we need to integrate the E2E to ensure that the additional parameters are used

**Review by jsilvela — APPROVED** [review]

**Pull request merged**
