### PR TITLE
feat: add metrics for pg_stat_checkpointer in v17+

### LINKED ISSUE #3411: [Bug]: PostgreSQL 17 removed some columns from `pg_stat_bgwriter` and introduced `pg_stat_checkpointer`
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Contact Details

_No response_

### Version

1.21.1

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

After the following ticket https://github.com/postgres/postgres/commit/96f052613f35d07d001c8dd2f284ca8d95f82d1b some columns changed and the monitoring metrics are failing in the development trunk of PostgreSQL 17-devel

### Cluster resource

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NiccoloFei**
Closes #3411

### CODE REVIEW

**Comment by NiccoloFei** [comment]
Because the query mapping needs to be unique (even tough the 2 queries are exclusive), I've distinguished the bgwriter metric's name in the following way:
* for PG17 and onward: `pg_stat_background_writer`
* for PG16 and lower: `pg_stat_bgwriter` (retaining the same name)

I've also thought about including and serving the 4 remaining bgwriter columns directly from the `pg_stat_checkpointer` query (on PG17+) but I figured it would be even more confusing this way, so I opted for the previous solution.

Tests running on: https://github.com/cloudnative-pg/postgres-trunk-containers/actions/runs/8881859306

**Review by sxd — APPROVED** [review]

**Comment by fcanovai** [comment]
I don't like the idea to generate metrics with different names from the same table, although on different postgres version.

Additionally, such changes should affect the grafana dashboard as well.

**Comment by mnencia** [comment]
Superseded by https://github.com/cloudnative-pg/cloudnative-pg/pull/4779

**Pull request closed without merging**
