### PR TITLE
fix(alerts): refine LastFailedArchiveTime to not trigger if a new backup has been successful in the meantime

### PR DESCRIPTION
**Pull request by davinkevin**
The current setup only checked the `cnpg_pg_stat_archiver_last_failed_time`, meaning if any backup failed at least once in the complete database life, this alert stays forever. The current implementation is simple and just compare the previous value to the last_archived_time.

### CODE REVIEW

**Comment by mnencia** [comment]
@davinkevin can you please fix the [DCO error](https://github.com/cloudnative-pg/cloudnative-pg/pull/1751/checks?check_run_id=12228516307)?

**Comment by davinkevin** [comment]
@mnencia It's now done 👍

**Comment by davinkevin** [comment]
@mnencia rebased again with main and ready for merge, except if you see something missing 😇

**Comment by jsilvela** [comment]
Sorry, I had this assigned and did not look at it. Doing the review tomorrow morning (EU), I promise.

**Comment by jsilvela** [comment]
Tested locally, this looks good. Waiting for a second review...

**Review by gbartolini — APPROVED** [review]

**Pull request merged**
