### PR TITLE
chore: improve operator logs in E2E tests

### PR DESCRIPTION
**Pull request by jsilvela**
This patch improves the collection and display of operator logs on test failure.
Now the operator logs will be filtered to collect only those logs that were
affecting the namespace of the test.

# Release notes

NONE

### CODE REVIEW

**Review by armru — APPROVED** [review]

**Comment by leonardoce** [comment]
Full E2e run: https://github.com/EnterpriseDB/cloudnative-pg/actions/runs/10561503530

**Review by leonardoce — APPROVED** [review]

**Pull request merged**
