### PR TITLE
chore: deprecating ubuntu-20.04 in favor of ubuntu-22.04 for GitHub actions

### PR DESCRIPTION
**Pull request by sxd**
The version 20.04 of the ubuntu runners it's about to go end of life, and we should start using the latest version 22.04

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

**Comment by litaocdl** [comment]
run from action directly: https://github.com/cloudnative-pg/cloudnative-pg/actions/runs/5152256652

**Review by jsilvela — APPROVED** [review]

**Pull request merged**
