### PR TITLE
docs: add predefined labels and annotations

### LINKED ISSUE #2740: Document predefined labels and annotations
At the moment we are not documenting the predefined labels and annotations. They are all defined in the pkg/utils/labels_annotations.go file.

Please add them to the Labels and Annotations page.

### PR DESCRIPTION
**Pull request by gbartolini**
Closes #2740

### CODE REVIEW

**Review by sxd — APPROVED** [review]

**Comment by mnencia** [comment]
IT misses documentation about https://github.com/cloudnative-pg/cloudnative-pg/blob/6ccb53531eb6558d9b648c108ea2bdf15c4284de/pkg/utils/fencing.go#L48-L56

**Comment by mnencia** [comment]
Another annotation is not present in that file

https://github.com/cloudnative-pg/cloudnative-pg/blob/e133fd93d884f9a1fd2ec048a676988274c8b59a/pkg/specs/pods.go#L48-L50

**Comment by mnencia** [comment]
https://github.com/cloudnative-pg/cloudnative-pg/blob/42be16aae9fdadd62bf95a63e36fac6005986cba/pkg/resources/labels_annotations.go#L24-L25

**Comment by mnencia** [comment]
https://github.com/cloudnative-pg/cloudnative-pg/blob/3282598882491037d1583f0dc413dfb9672e5b05/api/v1/cluster_types.go#L2825-L2831

**Comment by mnencia** [comment]
https://github.com/cloudnative-pg/cloudnative-pg/blob/9224ff37cb63f444e9adeae19b5c9765067e7210/pkg/reconciler/persistentvolumeclaim/status.go#L38-L40

**Comment by gbartolini** [comment]
I would do this as part of another ticket.

**Comment by gbartolini** [comment]
Please merge then continue with #2749 to centralize the labels and annotations

**Review by mnencia — APPROVED** [review]

**Pull request merged**
