### PR TITLE
feat: add `label-backup-name` flag to snapshot command

### LINKED ISSUE #2652: add an optional parameter: 'backupNameLabel' to snapshot plugin command
We recently added the backupName label for the snapshots created in a declarative way.

We should add this possibility to the snapshots made by the plugin too by adding a new optional parameter

### PR DESCRIPTION
**Pull request by armru**
Closes #2652

### CODE REVIEW

**Review by litaocdl — APPROVED** [review]

**Review by YanniHu1996 — APPROVED** [review]

**Comment by mnencia** [comment]
/ok-to-merge all E2E test failures are due to GitHub actions engine instability

**Review by mnencia — APPROVED** [review]

**Pull request merged**
