### PR TITLE
test: deprecate CreateNamespace

### LINKED ISSUE #2010: E2E: CreateNamespace should create and return a unique namespace
We should alter the func (env TestingEnvironment) CreateNamespace function to ensure uniqueness.
That function should create a unique Namespace and return its name.

We can think of several alternatives:

- use UUID’s to ensure uniqueness (but the resulting names would be long)

- add a go-routine-safe map data structure in TestingEnvironment where we could keep track of all namespaces created, and check for collisions

- have an atomic counter for namespaces. CreateNamespace() would reserve an entry in the counter, say “13”, then append the counter to the namespace argument provided by the user

This will ensure that we avoid conflicts during E2E runs

The issue was originally reported by @jsilvela

### PR DESCRIPTION
**Pull request by armru**
Closes #2010

### CODE REVIEW

**Comment by jsilvela** [comment]
I think the solution as is is incomplete, and needs further discussion.
The main issue is we keep basically the same interface: we provide a name, and create a namespace with that name.
Except, this may throw a runtime error if the namespace existed already…
In a way, this makes the new approach more brittle than the current one.

**Review by jsilvela — COMMENTED** [review]
I think the solution as is is incomplete, and needs further discussion.
The main issue is we keep basically the same interface: we provide a name, and create a namespace with that name.
Except, this may throw a runtime error if the namespace existed already…
In a way, this makes the new approach more brittle than the current one.

**Review by jsilvela — APPROVED** [review]

**Review by mnencia — APPROVED** [review]

**Pull request merged**
